GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "another title",
  "author": "another author",
  "url": "another url",
  "likes": 99
}