GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "another title---",
  "author": "another author---",
  "url": "another url---",
  "likes": 99,
  "user": "61b36330ce1ed411633d8fdc"
}
###
DELETE http://localhost:3003/api/blogs/61b39fd49d1ae6a7d507d686
###
PUT http://localhost:3003/api/blogs/61b23cc22d7004249af5e03b
Content-Type: application/json

{
  "title": "another title-",
  "author": "another author-",
  "url": "another url-",
  "likes": 99
}
###################################
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "blogs": [],
  "username": "beetroot1",
  "name": "beetroot user",
  "password": "suppass"
}
#####################################
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username":"beetroot",
  "password":"suppass"
}